// design/tokens.json → src/styles/tokens.css. `--check` fails on drift (CI).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

type Tokens = typeof import('../design/tokens.json');

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());

function lum(hex: string): number {
  const n = parseInt(hex.slice(1), 16);
  const ch = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map((v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * ch[0] + 0.7152 * ch[1] + 0.0722 * ch[2];
}

/** WCAG 2.x contrast ratio between two #rrggbb colors. */
export function contrast(a: string, b: string): number {
  const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p);
  return (x + 0.05) / (y + 0.05);
}

const block = (vars: Record<string, string>, prefix: string) =>
  Object.entries(vars)
    .map(([k, v]) => `  --${prefix}${kebab(k)}: ${v};`)
    .join('\n');

export function gen(t: Tokens): string {
  const base = [
    block(t.semantic.dark, 'c-'),
    block(t.ansi, 'ansi-'),
    t.space.slice(1).map((v, i) => `  --sp-${i + 1}: ${v}px;`).join('\n'),
    Object.entries(t.radius).map(([k, v]) => `  --r-${k}: ${v}px;`).join('\n'),
    t.type.scale.map((v, i) => `  --fs-${i + 1}: ${v / 16}rem;`).join('\n'),
    Object.entries(t.z).map(([k, v]) => `  --z-${k}: ${v};`).join('\n'),
    `  --ease: ${t.motion.ease};`,
    `  --d-fast: ${t.motion.fast}ms;\n  --d-base: ${t.motion.base}ms;\n  --d-slow: ${t.motion.slow}ms;`,
    `  --font-mono: "JetBrains Mono", "JetBrains Mono Fallback", ui-monospace, monospace;`,
    `  --font-mark: "VT323", var(--font-mono);`,
    `  color-scheme: dark;`,
  ].join('\n');
  const light = `${block(t.semantic.light, 'c-')}\n  color-scheme: light;`;
  return `/* generated by scripts/gen-tokens.ts from design/tokens.json. Do not edit. */
:root {
${base}
}
:root[data-theme="light"] {
${light}
}
@media (prefers-color-scheme: light) {
  :root:not([data-theme="dark"]) {
${light.replace(/^/gm, '  ')}
  }
}
`;
}

const OUT = fileURLToPath(new URL('../src/styles/tokens.css', import.meta.url));

if (import.meta.main) {
  const tokens: Tokens = JSON.parse(readFileSync(new URL('../design/tokens.json', import.meta.url), 'utf8'));
  const css = gen(tokens);
  if (process.argv.includes('--check')) {
    let current = '';
    try { current = readFileSync(OUT, 'utf8'); } catch { /* missing = drift */ }
    if (current !== css) {
      console.error('tokens.css is out of date. Run `bun run tokens`.');
      process.exit(1);
    }
  } else {
    writeFileSync(OUT, css);
    console.log('wrote', OUT);
  }
}
